spring.application.name=school
server.port=8090

# DATA SOURCE (Postgres)
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/school
spring.datasource.username=postgres
spring.datasource.password=grootan
#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=create
spring.jpa.hibernate.ddl-auto=update

# H2 Database
#spring.datasource.driverClassName=org.h2.Driver
#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:schoolApp
#spring.datasource.username=sa
#spring.datasource.password=password
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect


#KEYCLAOK-IDP
spring.KEYCLOAK_BASE_URL="http://localhost:8080/auth/realms/
spring.KEYCLOAK_REALM="school"
spring.KEYCLOAK_CLIENT_ID=""
spring.KEYCLOAK_CLIENT_SECRET=""

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

